script:
- npm install
- npm run data:setup
- npm run data:project
- npm run test
language: node_js
node_js:
- 8.1
branches:
  only:
  - master
  - develop
notifications:
  slack:
    secure: LmggH9gMk4pmxIfIJncPAj7u/CHMyWWXdvXXxarO3y/bdrr3ZqiwfEWLwy6Kdh1fsCCMlASSgn138NM1/wTgb8xRzfApTE+s0sZpXr8svmZPhiOguI3c7foVh01yZG+LLIAxX/NqRbhwaaEKvrj60hOxuN1IQ4rwZ4d3Ovc4B78tEfPPuzGQr3Tl2sW9W3ij5KK67qR3hltK8yGyuA6DPs0SbshQ6ENX1GWqDz4uGEa6JMBVc+FEd3aUlgads2ErHqvHhdDGEkDmyVspGXNf2LGtlSkjOoNPetTkmc/xQMsuK83E+yeEmNsTl6I/hC8rjCCJ0o6oEqLBK/TwMjRn4MIZ4bMOMPr56218a9+a60QwhDq4hDRDCc3AlV/Kxs06mvRGzmwkRymUTraC7cravW/THKj8HnfHEAb+CbuPULQe8pRCnimSI08zLRczDzD3jLz/sueDHQFHblMqayTY9+TWWOTp3LU8Dxuq6nnzvyJhDtExsrwivk/z/B9THOq7FvwZg1Kcni9ZJiqFyUGTNiSilT62OCqKDoUirTsdwjqVSHV8LBdkycnWU8tJKcG5DbnoQDE236JZXSeB+trrNDzMeuq4r52/rN1H5+HPGxePgJ9upQRVQtTbap0GwkcHA1tyiHCwmxP9mV3tmSSX7mbIRq2f3xcwEBLsGOh+ErI=
